api = "0.6"

[buildpack]
  homepage = "https://github.com/ForestEckhardt/gotip"
  id = "ForestEckhardt/gotip"
  name = "Paketo Gotip Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:golang:go:1.17.7:*:*:*:*:*:*:*"
    id = "go"
    licenses = ["BSD-3-Clause"]
    purl = "pkg:generic/go@go1.17.7?checksum=c108cd33b73b1911a02b697741df3dea43e01a5c4e08e409e8b3a0e3745d2b4d&download_url=https://dl.google.com/go/go1.17.7.src.tar.gz"
    sha256 = "aaedca1bc08ed3e79838ebe1d3f140c2b68e06f74c6d8683e803eced286f6384"
    source = "https://dl.google.com/go/go1.17.7.src.tar.gz"
    source_sha256 = "c108cd33b73b1911a02b697741df3dea43e01a5c4e08e409e8b3a0e3745d2b4d"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny"]
    uri = "https://deps.paketo.io/go/go_go1.17.7_linux_x64_bionic_aaedca1b.tgz"
    version = "1.17.7"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "go"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
